name: shared
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.15.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.0.0
  json_serializable: ^6.0.0
