name: browser_cli
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  hive_ce: ^2.15.1
  path: ^1.9.0
  shared:
    path: ../shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
